@startuml
left to right direction
skinparam DefaultTextAlignment center

node "Dispositivo Móvil (Smartphone/Tablet)" as Mobile {
    
    component "Interfaz" as I

    component "Aplicación Veterinaria\n(Flutter)" as AppFlutter
    
    component "Módulo de Compresión\nde Imágenes\n" as Compressor
    
    database "Almacenamiento local encriptado con RSA (SQLite)" as database1
    
    I -->AppFlutter: "Muestra segun rol"
    AppFlutter --> Compressor : "Optimizador de almacenamiento"
    Compressor -->database1: "Datos locales"
}

cloud "Despliegue en Railway del Backend" as Cloud1 {
    component "API REST\n(Ruby)" as API

}

cloud "Base de datos en Supabase" as Cloud2 {
    database "Almacenamiento local encriptado con RSA (Postgresql)" as database2

}

AppFlutter ====> API : " Protocolo HTTPS / REST \n (Header: Authorization Bearer JWT)"
API ====> database2 : "Protocolo HTTPS / REST \n (Header: User id)"

@enduml