-- VetCare workflow contract and upgrade migration.
-- Safe to apply after the historical migrations and on the new baseline.

do $$
begin
  if exists (select 1 from pg_type where typname = 'consultation_status') then
    alter type consultation_status add value if not exists 'pending';
    alter type consultation_status add value if not exists 'confirmed';
    alter type consultation_status add value if not exists 'in_progress';
  end if;
end $$;

alter table if exists public.veterinarians
  add column if not exists years_experience integer not null default 0,
  add column if not exists is_active boolean not null default true;

alter table if exists public.pets
  add column if not exists allergies text,
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'pets_client_profile_fkey'
  ) then
    alter table public.pets add constraint pets_client_profile_fkey
      foreign key (client_id) references public.users(id) on delete cascade;
  end if;
end $$;

alter table if exists public.consultations
  add column if not exists specialty_id bigint references public.specialties(id),
  add column if not exists vitals jsonb not null default '{}'::jsonb,
  add column if not exists started_at timestamptz,
  add column if not exists completed_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.medication_schedules
  add column if not exists frequency_hours integer,
  add column if not exists next_dose_at timestamptz;

alter table if exists public.treatment_adherence
  add column if not exists scheduled_for timestamptz,
  add column if not exists created_by uuid default auth.uid() references auth.users(id);

alter table if exists public.consultation_documents
  add column if not exists uploaded_by uuid default auth.uid() references auth.users(id),
  add column if not exists file_name text,
  add column if not exists storage_path text,
  add column if not exists file_url text,
  add column if not exists content_type text,
  add column if not exists size_bytes bigint;

alter table if exists public.legal_documents
  add column if not exists uploaded_by uuid default auth.uid() references auth.users(id),
  add column if not exists file_name text,
  add column if not exists storage_path text,
  add column if not exists file_url text;

alter table if exists public.morphological_records
  add column if not exists photo_url text;

alter table if exists public.epidemiological_alerts
  add column if not exists severity_level text not null default 'medium';

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  consultation_id bigint not null unique references public.consultations(id) on delete cascade,
  client_id uuid not null references auth.users(id) on delete cascade,
  veterinarian_id uuid not null references public.veterinarians(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text check (comment is null or char_length(comment) <= 1500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_alert_per_consultation
  on public.epidemiological_alerts(consultation_id)
  where consultation_id is not null;

create unique index if not exists uq_active_vet_slot
  on public.consultations(veterinarian_id, scheduled_at)
  where status::text <> 'cancelled';

create or replace function public.book_consultation(
  p_pet_id bigint,
  p_veterinarian_id uuid,
  p_specialty_id bigint,
  p_scheduled_at timestamptz,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  created_consultation public.consultations;
  slot_day integer := extract(dow from p_scheduled_at at time zone 'America/Lima');
  slot_time time := (p_scheduled_at at time zone 'America/Lima')::time;
begin
  if auth.uid() is null then
    return jsonb_build_object('success', false, 'code', 'UNAUTHENTICATED', 'message', 'Debes iniciar sesión.');
  end if;
  if not public.owns_pet(p_pet_id) then
    return jsonb_build_object('success', false, 'code', 'PET_FORBIDDEN', 'message', 'La mascota no pertenece al usuario.');
  end if;
  if p_scheduled_at <= now() then
    return jsonb_build_object('success', false, 'code', 'INVALID_DATE', 'message', 'La cita debe programarse en el futuro.');
  end if;
  if not exists (
    select 1 from public.veterinarians v
    where v.id = p_veterinarian_id and v.is_active
  ) then
    return jsonb_build_object('success', false, 'code', 'VET_NOT_FOUND', 'message', 'El veterinario no está disponible.');
  end if;
  if p_specialty_id is not null and not exists (
    select 1 from public.veterinarian_specialties vs
    where vs.veterinarian_id = p_veterinarian_id and vs.specialty_id = p_specialty_id
  ) then
    return jsonb_build_object('success', false, 'code', 'SPECIALTY_MISMATCH', 'message', 'El veterinario no atiende la especialidad elegida.');
  end if;
  if exists (
    select 1 from public.veterinarian_availability a
    where a.veterinarian_id = p_veterinarian_id
      and a.is_active
  ) and not exists (
    select 1 from public.veterinarian_availability a
    where a.veterinarian_id = p_veterinarian_id
      and a.day_of_week = slot_day
      and a.is_active
      and slot_time >= a.start_time
      and slot_time < a.end_time
  ) then
    return jsonb_build_object('success', false, 'code', 'OUTSIDE_AVAILABILITY', 'message', 'El horario está fuera de la disponibilidad del veterinario.');
  end if;

  insert into public.consultations (
    pet_id, veterinarian_id, specialty_id, scheduled_at, reason, status
  ) values (
    p_pet_id, p_veterinarian_id, p_specialty_id, p_scheduled_at, nullif(trim(p_reason), ''), 'pending'
  ) returning * into created_consultation;

  return jsonb_build_object(
    'success', true,
    'code', 'CONSULTATION_BOOKED',
    'message', 'Cita agendada correctamente.',
    'data', to_jsonb(created_consultation)
  );
exception
  when unique_violation then
    return jsonb_build_object('success', false, 'code', 'SLOT_TAKEN', 'message', 'Ese horario acaba de ser reservado. Elige otro.');
  when others then
    return jsonb_build_object('success', false, 'code', 'BOOKING_ERROR', 'message', 'No se pudo agendar la cita. Inténtalo nuevamente.');
end;
$$;

create or replace function public.start_consultation(p_consultation_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare updated_consultation public.consultations;
begin
  if not exists (
    select 1 from public.consultations c
    join public.veterinarians v on v.id = c.veterinarian_id
    where c.id = p_consultation_id and v.user_id = auth.uid()
  ) then
    return jsonb_build_object('success', false, 'code', 'CONSULTATION_FORBIDDEN', 'message', 'No puedes iniciar esta consulta.');
  end if;

  update public.consultations
  set status = 'in_progress', started_at = coalesce(started_at, now()), updated_at = now()
  where id = p_consultation_id
    and status::text in ('pending', 'scheduled', 'confirmed', 'in_progress')
  returning * into updated_consultation;

  if updated_consultation.id is null then
    return jsonb_build_object('success', false, 'code', 'INVALID_STATUS', 'message', 'La consulta ya fue finalizada o cancelada.');
  end if;
  return jsonb_build_object('success', true, 'code', 'CONSULTATION_STARTED', 'message', 'Consulta iniciada.', 'data', to_jsonb(updated_consultation));
end;
$$;

create or replace function public.complete_consultation(
  p_consultation_id bigint,
  p_diagnosis text,
  p_treatment text,
  p_notes text default null,
  p_is_contagious boolean default false,
  p_vitals jsonb default '{}'::jsonb,
  p_medications jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_consultation public.consultations;
  medication jsonb;
  owner_lat double precision;
  owner_lng double precision;
  computed_hash text;
begin
  if nullif(trim(p_diagnosis), '') is null or nullif(trim(p_treatment), '') is null then
    return jsonb_build_object('success', false, 'code', 'VALIDATION_ERROR', 'message', 'Diagnóstico y tratamiento son obligatorios.');
  end if;
  if jsonb_typeof(coalesce(p_medications, '[]'::jsonb)) <> 'array' then
    return jsonb_build_object('success', false, 'code', 'INVALID_MEDICATIONS', 'message', 'La medicación debe ser una lista.');
  end if;
  if not exists (
    select 1 from public.consultations c
    join public.veterinarians v on v.id = c.veterinarian_id
    where c.id = p_consultation_id and v.user_id = auth.uid()
  ) then
    return jsonb_build_object('success', false, 'code', 'CONSULTATION_FORBIDDEN', 'message', 'No puedes finalizar esta consulta.');
  end if;

  computed_hash := encode(digest(
    p_consultation_id::text || '|' || trim(p_diagnosis) || '|' || trim(p_treatment),
    'sha256'
  ), 'hex');

  update public.consultations
  set diagnosis = trim(p_diagnosis),
      treatment = trim(p_treatment),
      notes = nullif(trim(p_notes), ''),
      is_contagious = p_is_contagious,
      vitals = coalesce(p_vitals, '{}'::jsonb),
      status = 'completed',
      started_at = coalesce(started_at, now()),
      completed_at = now(),
      integrity_hash = computed_hash,
      updated_at = now()
  where id = p_consultation_id and status::text <> 'cancelled'
  returning * into updated_consultation;

  if updated_consultation.id is null then
    return jsonb_build_object('success', false, 'code', 'INVALID_STATUS', 'message', 'No se puede finalizar una consulta cancelada.');
  end if;

  delete from public.medication_schedules where consultation_id = p_consultation_id;
  for medication in select value from jsonb_array_elements(coalesce(p_medications, '[]'::jsonb))
  loop
    if nullif(trim(medication->>'name'), '') is not null then
      insert into public.medication_schedules (
        consultation_id, medication_name, dosage, frequency,
        frequency_hours, start_date, end_date, next_dose_at
      ) values (
        p_consultation_id,
        trim(medication->>'name'),
        nullif(trim(medication->>'dosage'), ''),
        nullif(trim(medication->>'frequency'), ''),
        nullif(medication->>'frequency_hours', '')::integer,
        coalesce(nullif(medication->>'start_date', '')::date, current_date),
        nullif(medication->>'end_date', '')::date,
        coalesce(nullif(medication->>'next_dose_at', '')::timestamptz, now())
      );
    end if;
  end loop;

  if p_is_contagious then
    select u.latitude, u.longitude into owner_lat, owner_lng
    from public.pets p join public.users u on u.id = p.client_id
    where p.id = updated_consultation.pet_id;

    insert into public.epidemiological_alerts (
      consultation_id, disease, latitude, longitude, radius_km, severity_level, is_active
    ) values (
      p_consultation_id, trim(p_diagnosis), owner_lat, owner_lng, 5.0, 'high', true
    ) on conflict (consultation_id) where consultation_id is not null do update set
      disease = excluded.disease,
      latitude = excluded.latitude,
      longitude = excluded.longitude,
      is_active = true,
      updated_at = now();
  end if;

  return jsonb_build_object(
    'success', true,
    'code', 'CONSULTATION_COMPLETED',
    'message', 'Consulta finalizada y firmada correctamente.',
    'data', to_jsonb(updated_consultation)
  );
exception when others then
  return jsonb_build_object('success', false, 'code', 'COMPLETION_ERROR', 'message', 'No se pudo finalizar la consulta. Inténtalo nuevamente.');
end;
$$;

create or replace function public.submit_review(
  p_consultation_id bigint,
  p_rating integer,
  p_comment text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare created_review public.reviews;
begin
  if p_rating not between 1 and 5 then
    return jsonb_build_object('success', false, 'code', 'INVALID_RATING', 'message', 'La calificación debe estar entre 1 y 5.');
  end if;
  if not exists (
    select 1 from public.consultations c
    join public.pets p on p.id = c.pet_id
    where c.id = p_consultation_id and p.client_id = auth.uid() and c.status::text = 'completed'
  ) then
    return jsonb_build_object('success', false, 'code', 'REVIEW_FORBIDDEN', 'message', 'Solo puedes evaluar consultas completadas de tus mascotas.');
  end if;

  insert into public.reviews (consultation_id, client_id, veterinarian_id, rating, comment)
  select c.id, auth.uid(), c.veterinarian_id, p_rating, nullif(trim(p_comment), '')
  from public.consultations c where c.id = p_consultation_id
  on conflict (consultation_id) do update set
    rating = excluded.rating,
    comment = excluded.comment,
    updated_at = now()
  returning * into created_review;

  return jsonb_build_object('success', true, 'code', 'REVIEW_SAVED', 'message', 'Reseña guardada.', 'data', to_jsonb(created_review));
end;
$$;

create or replace function public.available_slots(
  p_veterinarian_id uuid,
  p_date date
)
returns table(slot_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  with availability as (
    select a.*
    from public.veterinarian_availability a
    where a.veterinarian_id = p_veterinarian_id
      and a.day_of_week = extract(dow from p_date)::integer
      and a.is_active
  ), generated as (
    select candidate at time zone 'America/Lima' as slot_at
    from availability a
    cross join lateral generate_series(
      p_date + a.start_time,
      p_date + a.end_time - make_interval(mins => a.slot_duration_minutes),
      make_interval(mins => a.slot_duration_minutes)
    ) candidate
  )
  select g.slot_at
  from generated g
  where g.slot_at > now()
    and not exists (
      select 1 from public.consultations c
      where c.veterinarian_id = p_veterinarian_id
        and c.scheduled_at = g.slot_at
        and c.status::text <> 'cancelled'
    )
  order by g.slot_at;
$$;

grant execute on function public.book_consultation(bigint, uuid, bigint, timestamptz, text) to authenticated;
grant execute on function public.start_consultation(bigint) to authenticated;
grant execute on function public.complete_consultation(bigint, text, text, text, boolean, jsonb, jsonb) to authenticated;
grant execute on function public.submit_review(bigint, integer, text) to authenticated;
grant execute on function public.available_slots(uuid, date) to authenticated;

alter table public.reviews enable row level security;
drop policy if exists complete_reviews_read on public.reviews;
create policy complete_reviews_read on public.reviews for select to authenticated using (true);
drop policy if exists complete_reviews_owner on public.reviews;
create policy complete_reviews_owner on public.reviews for all to authenticated
  using (client_id = auth.uid()) with check (client_id = auth.uid());
