-- VetCare reproducible baseline.
-- This migration intentionally precedes the historical fix migrations so a
-- brand-new Supabase project can be created from this repository alone.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  first_name text not null default '',
  last_name text not null default '',
  phone text,
  document text,
  address text,
  profile_picture text,
  latitude double precision,
  longitude double precision,
  role text not null default 'client' check (role in ('client', 'veterinarian')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.veterinarians (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.users(id) on delete cascade,
  license_number text unique,
  years_experience integer not null default 0 check (years_experience >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.specialties (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  is_active boolean not null default true
);

create table if not exists public.veterinarian_specialties (
  veterinarian_id uuid not null references public.veterinarians(id) on delete cascade,
  specialty_id bigint not null references public.specialties(id) on delete cascade,
  primary key (veterinarian_id, specialty_id)
);

create table if not exists public.veterinarian_availability (
  id bigint generated by default as identity primary key,
  veterinarian_id uuid not null references public.veterinarians(id) on delete cascade,
  day_of_week integer not null check (day_of_week between 0 and 6),
  start_time time not null,
  end_time time not null,
  slot_duration_minutes integer not null default 30 check (slot_duration_minutes between 10 and 240),
  is_active boolean not null default true,
  constraint veterinarian_availability_time_check check (start_time < end_time),
  constraint uq_vet_availability_vet_day unique (veterinarian_id, day_of_week)
);

create table if not exists public.species (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_exotic boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.breeds (
  id bigint generated by default as identity primary key,
  name text not null,
  species_id bigint not null references public.species(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (name, species_id)
);

create table if not exists public.pets (
  id bigint generated by default as identity primary key,
  client_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 80),
  species_id bigint not null references public.species(id),
  breed_id bigint references public.breeds(id) on delete set null,
  sex_code char(1) check (sex_code in ('M', 'F')),
  birth_date date check (birth_date is null or birth_date <= current_date),
  weight_kg numeric(8,3) check (weight_kg is null or weight_kg > 0),
  microchip text unique,
  photo_url text,
  allergies text,
  is_exotic boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.consultations (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  veterinarian_id uuid not null references public.veterinarians(id),
  specialty_id bigint references public.specialties(id),
  scheduled_at timestamptz not null,
  reason text,
  diagnosis text,
  treatment text,
  notes text,
  vitals jsonb not null default '{}'::jsonb,
  status text not null default 'pending'
    check (status in ('pending', 'scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled')),
  is_contagious boolean not null default false,
  integrity_hash text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_active_vet_slot
  on public.consultations(veterinarian_id, scheduled_at)
  where status <> 'cancelled';
create index if not exists idx_consultations_pet on public.consultations(pet_id, scheduled_at desc);
create index if not exists idx_consultations_vet on public.consultations(veterinarian_id, scheduled_at desc);

create table if not exists public.consultation_documents (
  id bigint generated by default as identity primary key,
  consultation_id bigint not null references public.consultations(id) on delete cascade,
  uploaded_by uuid not null default auth.uid() references auth.users(id),
  file_name text not null,
  storage_path text not null unique,
  file_url text,
  content_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  doc_type text not null default 'attachment',
  created_at timestamptz not null default now()
);

create table if not exists public.medication_schedules (
  id bigint generated by default as identity primary key,
  consultation_id bigint not null references public.consultations(id) on delete cascade,
  medication_name text not null,
  dosage text,
  frequency text,
  frequency_hours integer check (frequency_hours is null or frequency_hours between 1 and 168),
  start_date date not null default current_date,
  end_date date,
  next_dose_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint medication_date_check check (end_date is null or end_date >= start_date)
);

create table if not exists public.treatment_adherence (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.medication_schedules(id) on delete cascade,
  taken_at timestamptz not null default now(),
  scheduled_for timestamptz,
  notes text,
  created_by uuid not null default auth.uid() references auth.users(id)
);

create table if not exists public.epidemiological_alerts (
  id bigint generated by default as identity primary key,
  consultation_id bigint references public.consultations(id) on delete cascade,
  disease text not null,
  latitude double precision,
  longitude double precision,
  radius_km numeric(8,2) not null default 5.0 check (radius_km > 0),
  severity_level text not null default 'medium'
    check (severity_level in ('low', 'medium', 'high', 'critical')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.morphological_records (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  recorded_at timestamptz not null default now(),
  length_cm numeric(8,2),
  weight_kg numeric(8,3),
  scale_condition text,
  color_pattern text,
  photo_url text,
  notes text
);

create table if not exists public.legal_documents (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  uploaded_by uuid not null default auth.uid() references auth.users(id),
  doc_type text not null,
  file_name text not null,
  storage_path text not null unique,
  file_url text,
  expires_at date,
  notes text,
  uploaded_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  consultation_id bigint not null unique references public.consultations(id) on delete cascade,
  client_id uuid not null references auth.users(id) on delete cascade,
  veterinarian_id uuid not null references public.veterinarians(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text check (comment is null or char_length(comment) <= 1500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Seed IDs 1..9 deliberately match the historical migration's original
-- assumptions. Later migrations normalize English duplicates to Spanish.
insert into public.species (name, is_exotic) values
  ('Perro', false), ('Gato', false), ('Ave', false),
  ('Conejo', false), ('Hámster', false), ('Cobayo', false),
  ('Pez', false), ('Reptil', true), ('Exótico', true),
  ('Tortuga', true), ('Loro', false), ('Serpiente', true),
  ('Chinchilla', false), ('Hurón', false), ('Iguana', true)
on conflict (name) do update set is_exotic = excluded.is_exotic;

insert into public.specialties (name, icon) values
  ('Medicina General', 'medical_services'),
  ('Cirugía', 'content_cut'),
  ('Dermatología', 'dermatology'),
  ('Odontología', 'dentistry'),
  ('Animales Exóticos', 'pets'),
  ('Cardiología', 'cardiology'),
  ('Oftalmología', 'visibility')
on conflict (name) do nothing;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['users','veterinarians','species','breeds','pets','consultations','epidemiological_alerts','reviews']
  loop
    execute format('drop trigger if exists trg_%I_updated_at on public.%I', table_name, table_name);
    execute format('create trigger trg_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name, table_name);
  end loop;
end $$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_role text := case when new.raw_user_meta_data->>'role' = 'veterinarian'
    then 'veterinarian' else 'client' end;
  created_vet_id uuid;
  general_specialty_id bigint;
begin
  insert into public.users (
    id, email, first_name, last_name, phone, document, address, role
  ) values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'first_name', ''),
    coalesce(new.raw_user_meta_data->>'last_name', ''),
    nullif(new.raw_user_meta_data->>'phone', ''),
    nullif(new.raw_user_meta_data->>'document', ''),
    nullif(new.raw_user_meta_data->>'address', ''),
    requested_role
  ) on conflict (id) do update set
    email = excluded.email,
    first_name = excluded.first_name,
    last_name = excluded.last_name,
    phone = coalesce(excluded.phone, public.users.phone),
    document = coalesce(excluded.document, public.users.document),
    address = coalesce(excluded.address, public.users.address),
    role = excluded.role;

  if requested_role = 'veterinarian' then
    insert into public.veterinarians (user_id, license_number)
    values (new.id, nullif(new.raw_user_meta_data->>'document', ''))
    on conflict (user_id) do update
      set license_number = coalesce(excluded.license_number, public.veterinarians.license_number);
    select id into created_vet_id from public.veterinarians where user_id = new.id;
    select id into general_specialty_id from public.specialties where name = 'Medicina General';
    if general_specialty_id is not null then
      insert into public.veterinarian_specialties (veterinarian_id, specialty_id)
      values (created_vet_id, general_specialty_id)
      on conflict do nothing;
    end if;
    insert into public.veterinarian_availability (
      veterinarian_id, day_of_week, start_time, end_time, slot_duration_minutes, is_active
    )
    select created_vet_id, day_number, '09:00'::time, '18:00'::time, 30, true
    from generate_series(1, 6) as day_number
    on conflict (veterinarian_id, day_of_week) do nothing;
  else
    insert into public.clients (user_id) values (new.id)
    on conflict (user_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of raw_user_meta_data, email on auth.users
  for each row execute function public.handle_new_auth_user();

create or replace function public.is_veterinarian()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.veterinarians where user_id = auth.uid() and is_active);
$$;

create or replace function public.owns_pet(p_pet_id bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.pets where id = p_pet_id and client_id = auth.uid());
$$;

create or replace function public.can_access_consultation(p_consultation_id bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(
    select 1
    from public.consultations c
    join public.pets p on p.id = c.pet_id
    join public.veterinarians v on v.id = c.veterinarian_id
    where c.id = p_consultation_id
      and (p.client_id = auth.uid() or v.user_id = auth.uid())
  );
$$;

alter table public.users enable row level security;
alter table public.clients enable row level security;
alter table public.veterinarians enable row level security;
alter table public.specialties enable row level security;
alter table public.veterinarian_specialties enable row level security;
alter table public.veterinarian_availability enable row level security;
alter table public.species enable row level security;
alter table public.breeds enable row level security;
alter table public.pets enable row level security;
alter table public.consultations enable row level security;
alter table public.consultation_documents enable row level security;
alter table public.medication_schedules enable row level security;
alter table public.treatment_adherence enable row level security;
alter table public.epidemiological_alerts enable row level security;
alter table public.morphological_records enable row level security;
alter table public.legal_documents enable row level security;
alter table public.reviews enable row level security;

drop policy if exists baseline_users_select on public.users;
create policy baseline_users_select on public.users for select to authenticated
  using (id = auth.uid() or public.is_veterinarian());
drop policy if exists baseline_users_update on public.users;
create policy baseline_users_update on public.users for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists baseline_clients_own on public.clients;
create policy baseline_clients_own on public.clients for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists baseline_vets_read on public.veterinarians;
create policy baseline_vets_read on public.veterinarians for select to authenticated using (is_active or user_id = auth.uid());
drop policy if exists baseline_vets_update on public.veterinarians;
create policy baseline_vets_update on public.veterinarians for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists baseline_catalog_read on public.species;
create policy baseline_catalog_read on public.species for select using (true);
drop policy if exists baseline_breeds_read on public.breeds;
create policy baseline_breeds_read on public.breeds for select using (true);
drop policy if exists baseline_specialties_read on public.specialties;
create policy baseline_specialties_read on public.specialties for select using (true);
drop policy if exists baseline_vet_specialties_read on public.veterinarian_specialties;
create policy baseline_vet_specialties_read on public.veterinarian_specialties for select using (true);
drop policy if exists baseline_vet_specialties_write on public.veterinarian_specialties;
create policy baseline_vet_specialties_write on public.veterinarian_specialties for all to authenticated
  using (exists(select 1 from public.veterinarians v where v.id = veterinarian_id and v.user_id = auth.uid()))
  with check (exists(select 1 from public.veterinarians v where v.id = veterinarian_id and v.user_id = auth.uid()));

drop policy if exists baseline_availability_read on public.veterinarian_availability;
create policy baseline_availability_read on public.veterinarian_availability for select to authenticated using (true);
drop policy if exists baseline_availability_write on public.veterinarian_availability;
create policy baseline_availability_write on public.veterinarian_availability for all to authenticated
  using (exists(select 1 from public.veterinarians v where v.id = veterinarian_id and v.user_id = auth.uid()))
  with check (exists(select 1 from public.veterinarians v where v.id = veterinarian_id and v.user_id = auth.uid()));

drop policy if exists baseline_pets_access on public.pets;
create policy baseline_pets_access on public.pets for select to authenticated
  using (client_id = auth.uid() or public.is_veterinarian());
drop policy if exists baseline_pets_owner_write on public.pets;
create policy baseline_pets_owner_write on public.pets for all to authenticated
  using (client_id = auth.uid()) with check (client_id = auth.uid());

drop policy if exists baseline_consultations_access on public.consultations;
create policy baseline_consultations_access on public.consultations for select to authenticated
  using (public.can_access_consultation(id));
drop policy if exists baseline_consultations_client_insert on public.consultations;
create policy baseline_consultations_client_insert on public.consultations for insert to authenticated
  with check (public.owns_pet(pet_id));
drop policy if exists baseline_consultations_vet_update on public.consultations;
create policy baseline_consultations_vet_update on public.consultations for update to authenticated
  using (exists(select 1 from public.veterinarians v where v.id = veterinarian_id and v.user_id = auth.uid()))
  with check (exists(select 1 from public.veterinarians v where v.id = veterinarian_id and v.user_id = auth.uid()));

drop policy if exists baseline_consultation_docs_access on public.consultation_documents;
create policy baseline_consultation_docs_access on public.consultation_documents for select to authenticated
  using (public.can_access_consultation(consultation_id));
drop policy if exists baseline_consultation_docs_insert on public.consultation_documents;
create policy baseline_consultation_docs_insert on public.consultation_documents for insert to authenticated
  with check (uploaded_by = auth.uid() and public.can_access_consultation(consultation_id));
drop policy if exists baseline_consultation_docs_delete on public.consultation_documents;
create policy baseline_consultation_docs_delete on public.consultation_documents for delete to authenticated
  using (uploaded_by = auth.uid());

drop policy if exists baseline_medication_access on public.medication_schedules;
create policy baseline_medication_access on public.medication_schedules for select to authenticated
  using (public.can_access_consultation(consultation_id));
drop policy if exists baseline_medication_vet_write on public.medication_schedules;
create policy baseline_medication_vet_write on public.medication_schedules for all to authenticated
  using (public.can_access_consultation(consultation_id) and public.is_veterinarian())
  with check (public.can_access_consultation(consultation_id) and public.is_veterinarian());

drop policy if exists baseline_adherence_access on public.treatment_adherence;
create policy baseline_adherence_access on public.treatment_adherence for select to authenticated
  using (exists(select 1 from public.medication_schedules m where m.id = schedule_id and public.can_access_consultation(m.consultation_id)));
drop policy if exists baseline_adherence_client_insert on public.treatment_adherence;
create policy baseline_adherence_client_insert on public.treatment_adherence for insert to authenticated
  with check (created_by = auth.uid() and exists(
    select 1 from public.medication_schedules m
    join public.consultations c on c.id = m.consultation_id
    where m.id = schedule_id and public.owns_pet(c.pet_id)
  ));

drop policy if exists baseline_alerts_read on public.epidemiological_alerts;
create policy baseline_alerts_read on public.epidemiological_alerts for select to authenticated using (is_active);

drop policy if exists baseline_morphological_access on public.morphological_records;
create policy baseline_morphological_access on public.morphological_records for select to authenticated
  using (public.owns_pet(pet_id) or public.is_veterinarian());
drop policy if exists baseline_morphological_write on public.morphological_records;
create policy baseline_morphological_write on public.morphological_records for all to authenticated
  using (public.owns_pet(pet_id) or public.is_veterinarian())
  with check (public.owns_pet(pet_id) or public.is_veterinarian());

drop policy if exists baseline_legal_documents_access on public.legal_documents;
create policy baseline_legal_documents_access on public.legal_documents for select to authenticated
  using (public.owns_pet(pet_id) or public.is_veterinarian());
drop policy if exists baseline_legal_documents_write on public.legal_documents;
create policy baseline_legal_documents_write on public.legal_documents for all to authenticated
  using (uploaded_by = auth.uid() and public.owns_pet(pet_id))
  with check (uploaded_by = auth.uid() and public.owns_pet(pet_id));

drop policy if exists baseline_reviews_read on public.reviews;
create policy baseline_reviews_read on public.reviews for select to authenticated using (true);
drop policy if exists baseline_reviews_client_write on public.reviews;
create policy baseline_reviews_client_write on public.reviews for all to authenticated
  using (client_id = auth.uid()) with check (client_id = auth.uid());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('profiles', 'profiles', true, 5242880, array['image/jpeg','image/png','image/webp']),
  ('pet-images', 'pet-images', true, 5242880, array['image/jpeg','image/png','image/webp']),
  ('consultation-docs', 'consultation-docs', false, 10485760, array['application/pdf','image/jpeg','image/png']),
  ('legal-docs', 'legal-docs', false, 10485760, array['application/pdf','image/jpeg','image/png'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists baseline_storage_profiles_insert on storage.objects;
create policy baseline_storage_profiles_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'profiles' and (storage.foldername(name))[2] = auth.uid()::text);
drop policy if exists baseline_storage_profiles_update on storage.objects;
create policy baseline_storage_profiles_update on storage.objects for update to authenticated
  using (bucket_id = 'profiles' and owner_id = auth.uid()::text);

drop policy if exists baseline_storage_pet_insert on storage.objects;
create policy baseline_storage_pet_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'pet-images' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists baseline_storage_pet_update on storage.objects;
create policy baseline_storage_pet_update on storage.objects for update to authenticated
  using (bucket_id = 'pet-images' and owner_id = auth.uid()::text);

drop policy if exists baseline_storage_consultation_access on storage.objects;
create policy baseline_storage_consultation_access on storage.objects for select to authenticated
  using (
    bucket_id = 'consultation-docs'
    and public.can_access_consultation(nullif((storage.foldername(name))[2], '')::bigint)
  );
drop policy if exists baseline_storage_consultation_insert on storage.objects;
create policy baseline_storage_consultation_insert on storage.objects for insert to authenticated
  with check (
    bucket_id = 'consultation-docs'
    and (storage.foldername(name))[1] = auth.uid()::text
    and public.can_access_consultation(nullif((storage.foldername(name))[2], '')::bigint)
  );

drop policy if exists baseline_storage_legal_access on storage.objects;
create policy baseline_storage_legal_access on storage.objects for select to authenticated
  using (
    bucket_id = 'legal-docs'
    and (public.owns_pet(nullif((storage.foldername(name))[2], '')::bigint) or public.is_veterinarian())
  );
drop policy if exists baseline_storage_legal_insert on storage.objects;
create policy baseline_storage_legal_insert on storage.objects for insert to authenticated
  with check (
    bucket_id = 'legal-docs'
    and (storage.foldername(name))[1] = auth.uid()::text
    and public.owns_pet(nullif((storage.foldername(name))[2], '')::bigint)
  );
